name:                gh-projects-discord
version:             0.2.0
github:              "yutotakano/gh-projects-discord"
license:             MIT
author:              "Yuto Takano"
maintainer:          "moa17stock@gmail.com"
copyright:           "2021 Yuto Takano"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        Relay GitHub Project webhooks to Discord

dependencies:
- base >= 4.7 && < 5
- scotty
- bytestring
- aeson
- http-types
- text
- unordered-containers
- http-conduit

default-extensions: OverloadedStrings

library:
  source-dirs: src

executables:
  gh-projects-discord-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gh-projects-discord

tests:
  gh-projects-discord-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gh-projects-discord
